use std::ptr;
use std::slice;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Mutex,
};
use std::thread;
use std::time::Duration;

#[cfg(unix)]
use libc;
#[cfg(unix)]
use nix::{
    sys::{
        ptrace,
        wait::{waitpid, WaitStatus},
    },
    unistd::Pid,
};

#[cfg(target_family = "windows")]
use windows_sys::core::GUID;
#[cfg(target_family = "windows")]
use windows_sys::Win32::Foundation::ERROR_SUCCESS;
#[cfg(target_family = "windows")]
use windows_sys::Win32::System::Diagnostics::Etw::*;

#[cfg(unix)]
pub fn monitor_ptrace(
    child_pid: i32,
    api_calls: Arc<Mutex<Vec<String>>>,
    stop_flag: Arc<AtomicBool>,
) -> Option<i32> {
    let pid = Pid::from_raw(child_pid);
    let mut calls = api_calls.lock().unwrap();
    calls.push(format!("ptrace:attaching pid={}", child_pid));
    drop(calls);

    // A normally spawned child is not being traced yet. Waiting for a stop
    // before PTRACE_ATTACH can block forever and silently produces no syscall
    // telemetry. Attach first, then consume the SIGSTOP generated by ptrace.
    if let Err(err) = ptrace::attach(pid) {
        let mut guard = api_calls.lock().unwrap();
        guard.push(format!("ptrace:attach_failed:{}", err));
        return None;
    }

    let mut calls = api_calls.lock().unwrap();
    calls.push(format!("ptrace:attached pid={}", child_pid));
    drop(calls);

    if let Err(err) = waitpid(pid, None) {
        let mut guard = api_calls.lock().unwrap();
        guard.push(format!("ptrace:waitpid_error:{}", err));
        return None;
    }

    if let Err(err) = ptrace::setoptions(
        pid,
        ptrace::Options::PTRACE_O_TRACESYSGOOD
            | ptrace::Options::PTRACE_O_TRACEFORK
            | ptrace::Options::PTRACE_O_TRACEVFORK
            | ptrace::Options::PTRACE_O_TRACECLONE,
    ) {
        let mut calls = api_calls.lock().unwrap();
        calls.push(format!("ptrace:setoptions_failed:{}", err));
    }

    if let Err(err) = ptrace::syscall(pid, None) {
        let mut calls = api_calls.lock().unwrap();
        calls.push(format!("ptrace:syscall_continue_failed:{}", err));
    }

    while !stop_flag.load(Ordering::SeqCst) {
        match waitpid(pid, None) {
            Ok(WaitStatus::Exited(_, code)) => {
                let mut calls = api_calls.lock().unwrap();
                calls.push(format!("ptrace:exited:{}", code));
                return Some(code);
            }
            Ok(WaitStatus::Signaled(_, sig, _)) => {
                let mut calls = api_calls.lock().unwrap();
                calls.push(format!("ptrace:signaled:{}", sig));
                return Some(128 + sig as i32);
            }
            Ok(WaitStatus::Stopped(_, _sig)) => {
                if let Ok(regs) = ptrace::getregs(pid) {
                    let name = syscall_name(regs.orig_rax as i64).unwrap_or("unknown");
                    let mut calls = api_calls.lock().unwrap();
                    calls.push(format!("ptrace:syscall:{}", name));
                }
                let _ = ptrace::syscall(pid, None);
            }
            Ok(WaitStatus::PtraceSyscall(_)) => {
                let _ = ptrace::syscall(pid, None);
            }
            Ok(_) => {
                let _ = ptrace::syscall(pid, None);
            }
            Err(err) => {
                let mut calls = api_calls.lock().unwrap();
                calls.push(format!("ptrace:waitpid_error:{}", err));
                return None;
            }
        }
    }
    None
}

#[cfg(target_family = "windows")]
pub fn monitor_etw(
    target_pid: u32,
    api_calls: Arc<Mutex<Vec<String>>>,
    stop_flag: Arc<AtomicBool>,
) {
    unsafe {
        let session_name: Vec<u16> = "EverbloomSecuritySandboxSession\0".encode_utf16().collect();
        let mut properties: EVENT_TRACE_PROPERTIES = std::mem::zeroed();
        properties.Wnode.BufferSize = std::mem::size_of::<EVENT_TRACE_PROPERTIES>() as u32;
        properties.Wnode.Flags = 0;
        properties.Wnode.ClientContext = 0;
        properties.BufferSize = std::mem::size_of::<EVENT_TRACE_PROPERTIES>() as u32;
        properties.LogFileMode = EVENT_TRACE_REAL_TIME_MODE;
        properties.EnableFlags = EVENT_TRACE_FLAG_PROCESS
            | EVENT_TRACE_FLAG_FILE_IO
            | EVENT_TRACE_FLAG_NETWORK_TCPIP
            | EVENT_TRACE_FLAG_REGISTRY;

        let mut session_handle: CONTROLTRACE_HANDLE = std::mem::zeroed();
        let status = StartTraceW(&mut session_handle, session_name.as_ptr(), &mut properties);
        if status != ERROR_SUCCESS {
            let mut calls = api_calls.lock().unwrap();
            calls.push(format!("etw:start_failed:{}", status));
            return;
        }

        {
            let mut calls = api_calls.lock().unwrap();
            calls.push(format!("etw:session_started pid={}", target_pid));
        }

        // The event-record callback below parses the enabled kernel providers
        // and extracts the concrete file/registry/process/network actions from
        // each record's payload, so the sandbox report carries rich telemetry
        // rather than bare event ids.

        let mut log = std::mem::zeroed::<EVENT_TRACE_LOGFILEW>();
        log.LoggerName = session_name.as_ptr() as _;
        log.Anonymous1.ProcessTraceMode =
            PROCESS_TRACE_MODE_REAL_TIME | PROCESS_TRACE_MODE_EVENT_RECORD;
        log.Anonymous2.EventRecordCallback = Some(etw_event_record_callback);
        // ETW copies this context into EVENT_RECORD.UserContext for each
        // callback. Keeping it on the trace handle removes the process-global
        // raw pointer and allows multiple monitor sessions to coexist.
        let raw_api_calls = Arc::into_raw(api_calls.clone()) as usize;
        log.Context = raw_api_calls as *mut core::ffi::c_void;

        let trace_handle = OpenTraceW(&mut log);
        if trace_handle.Value == 0 {
            drop(Arc::from_raw(raw_api_calls as *const Mutex<Vec<String>>));
            let mut calls = api_calls.lock().unwrap();
            calls.push("etw:open_trace_failed".to_string());
            let _ = ControlTraceW(
                session_handle,
                session_name.as_ptr(),
                &mut properties,
                EVENT_TRACE_CONTROL_STOP,
            );
            return;
        }

        let trace_worker = thread::spawn(move || {
            let handles: [PROCESSTRACE_HANDLE; 1] = [trace_handle];
            let status = ProcessTrace(handles.as_ptr(), 1, ptr::null_mut(), ptr::null_mut());
            if status != ERROR_SUCCESS {
                let calls = &*(raw_api_calls as *const Mutex<Vec<String>>);
                let mut guard = calls.lock().unwrap();
                guard.push(format!("etw:process_trace_failed:{}", status));
            }
            drop(Arc::from_raw(raw_api_calls as *const Mutex<Vec<String>>));
        });

        while !stop_flag.load(Ordering::SeqCst) {
            thread::sleep(Duration::from_millis(250));
        }

        let _ = ControlTraceW(
            session_handle,
            session_name.as_ptr(),
            &mut properties,
            EVENT_TRACE_CONTROL_STOP,
        );
        let _ = trace_worker.join();
    }
}

#[cfg(target_family = "windows")]
unsafe extern "system" fn etw_event_record_callback(record: *mut EVENT_RECORD) {
    if record.is_null() {
        return;
    }

    let raw_ptr = (*record).UserContext as *const Mutex<Vec<String>>;
    if raw_ptr.is_null() {
        return;
    }

    let event = &*record;
    let header = &event.EventHeader;
    let desc = header.EventDescriptor;
    let provider = format_guid(&header.ProviderId);
    let timestamp = header.TimeStamp;

    // Best-effort payload decoding for the kernel providers the session
    // enables. Classic kernel records store their primary object name as a
    // USHORT char-count followed by UTF-16LE code units after the fixed-size
    // MOF prefix; `extract_utf16_target` pulls that string so the entry below
    // records e.g. `etw:file:C:\Windows\...` instead of a bare event id.
    let category = kernel_event_category(&header.ProviderId, desc.Id);
    let user_data = slice::from_raw_parts(event.UserData as *const u8, event.UserDataLength as usize);
    let entry = if let Some((kind, target)) =
        category.and_then(|kind| extract_utf16_target(user_data).map(|target| (kind, target)))
    {
        format!(
            "etw:{}:{} (pid={} tid={} id={} opcode={} provider={} ts={})",
            kind,
            cap_etw_target(&target),
            header.ProcessId,
            header.ThreadId,
            desc.Id,
            desc.Opcode,
            provider,
            timestamp,
        )
    } else {
        format!(
            "etw:event pid={} tid={} provider={} id={} opcode={} flags={} ts={}",
            header.ProcessId,
            header.ThreadId,
            provider,
            desc.Id,
            desc.Opcode,
            header.Flags,
            timestamp,
        )
    };

    let calls = &*raw_ptr;
    let mut guard = calls.lock().unwrap();
    guard.push(entry);
    let len = guard.len();
    if len > 256 {
        guard.drain(..len - 256);
    }
}

#[cfg(target_family = "windows")]
fn guid_matches(guid: &GUID, data1: u32, data2: u16, data3: u16, data4: [u8; 8]) -> bool {
    guid.data1 == data1 && guid.data2 == data2 && guid.data3 == data3 && guid.data4 == data4
}

/// Classifies an ETW record by provider GUID into the kernel action families
/// the session subscribes to. The NT Kernel Logger uses the classic providers
/// below; the modern kernel providers use a distinct GUID space while carrying
/// the same observable actions. Event-id sub-classification is intentionally
/// provider-specific and left to the caller that consumes the raw payload.
#[cfg(target_family = "windows")]
fn kernel_event_category(provider: &GUID, _event_id: u16) -> Option<&'static str> {
    if guid_matches(
        provider,
        0x90cb_dc39,
        0x4a3e,
        0x11d1,
        [0x84, 0xf4, 0x00, 0x00, 0xf8, 0x04, 0x64, 0xe3],
    ) || guid_matches(
        provider,
        0xedd0_8927,
        0x9cc4,
        0x4e65,
        [0xb9, 0x70, 0xc2, 0x56, 0x0f, 0xb5, 0xc2, 0x89],
    ) {
        Some("file")
    } else if guid_matches(
        provider,
        0xae53_722e,
        0xc863,
        0x11d2,
        [0xb9, 0x59, 0x00, 0xc0, 0x4f, 0x79, 0xf8, 0xd2],
    ) {
        Some("reg")
    } else if guid_matches(
        provider,
        0x3d6f_a8d0,
        0xfe05,
        0x11d0,
        [0x95, 0xda, 0x00, 0xc0, 0x4f, 0xd9, 0x19, 0xb1],
    ) || guid_matches(
        provider,
        0x22fb_2cd6,
        0x0e7b,
        0x422b,
        [0xa0, 0xc7, 0x2f, 0xad, 0x1f, 0xd0, 0xe7, 0x16],
    ) {
        Some("process")
    } else if guid_matches(
        provider,
        0x9a28_0ac0,
        0xc8e0,
        0x11d1,
        [0x84, 0xe2, 0x00, 0xc0, 0x4f, 0xb9, 0x98, 0xa2],
    ) {
        Some("net")
    } else {
        None
    }
}

#[cfg(target_family = "windows")]
fn cap_etw_target(target: &str) -> String {
    let mut clipped: String = target.chars().take(256).collect();
    if target.chars().count() > 256 {
        clipped.push_str("...");
    }
    clipped
}

/// Extracts the longest printable length-prefixed UTF-16LE string from a
/// kernel ETW record payload.
///
/// The classic kernel providers store the primary object name (file path,
/// registry key, process image, or peer endpoint) as a USHORT character-count
/// followed by UTF-16LE code units after the event's fixed-size fields. This
/// scanner walks every even offset for a plausible (count, units) pair. It is
/// deliberately conservative -- control characters, NULs, lone surrogates and
/// U+FFFD are rejected -- so malformed or non-string payloads degrade to the
/// generic `etw:event ...` entry instead of producing corrupt telemetry.
#[cfg(target_family = "windows")]
fn extract_utf16_target(user_data: &[u8]) -> Option<String> {
    let mut best: Option<(usize, Vec<u16>)> = None;
    let mut offset = 0usize;
    while offset + 2 <= user_data.len() {
        let len_chars = u16::from_le_bytes([user_data[offset], user_data[offset + 1]]) as usize;
        if (3..=1024).contains(&len_chars) {
            let bytes_needed = len_chars * 2;
            if offset + 2 + bytes_needed <= user_data.len() {
                let units: Vec<u16> = (0..len_chars)
                    .map(|index| {
                        let base = offset + 2 + index * 2;
                        u16::from_le_bytes([user_data[base], user_data[base + 1]])
                    })
                    .collect();
                let readable = units.iter().all(|unit| {
                    let printable = (0x20..=0x7e).contains(unit) || *unit >= 0x80;
                    let forbidden = *unit == 0 || *unit == 0xfffd || (0x0..0x20).contains(unit);
                    printable && !forbidden
                });
                if readable && best.as_ref().map_or(true, |(best_len, _)| len_chars > *best_len) {
                    best = Some((len_chars, units));
                }
            }
        }
        offset += 2;
    }
    best.map(|(_, units)| String::from_utf16_lossy(&units))
}

#[cfg(all(target_family = "windows", test))]
mod etw_parse_tests {
    use super::*;

    fn classic_file_io_payload(path: &str) -> Vec<u8> {
        let units: Vec<u16> = path.encode_utf16().collect();
        let mut payload = vec![1u8, 2, 3, 4, 5, 6, 7, 8]; // file object
        payload.extend_from_slice(&0u32.to_le_bytes()); // status
        payload.extend_from_slice(&0u32.to_le_bytes()); // disposition
        payload.extend_from_slice(&0u32.to_le_bytes()); // attributes
        payload.extend_from_slice(&0u32.to_le_bytes()); // share access
        payload.extend_from_slice(&(units.len() as u16).to_le_bytes());
        for unit in units {
            payload.extend_from_slice(&unit.to_le_bytes());
        }
        payload
    }

    #[test]
    fn classic_file_io_record_yields_file_path() {
        let path = "C:\\Windows\\System32\\evil.exe";
        let extracted = extract_utf16_target(&classic_file_io_payload(path)).expect("target extracted");
        assert_eq!(extracted, path);
    }

    #[test]
    fn registry_record_yields_key_name() {
        let key = "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";
        let units: Vec<u16> = key.encode_utf16().collect();
        let mut payload = vec![0u8; 16];
        payload.extend_from_slice(&(units.len() as u16).to_le_bytes());
        for unit in units {
            payload.extend_from_slice(&unit.to_le_bytes());
        }
        assert_eq!(extract_utf16_target(&payload).unwrap(), key);
    }

    #[test]
    fn longest_embedded_string_wins() {
        let short = "C:\\tmp";
        let long = "C:\\Program Files\\Mozilla Firefox\\firefox.exe";
        let mut combined = classic_file_io_payload(short);
        combined.extend_from_slice(&classic_file_io_payload(long)[..]);
        assert_eq!(extract_utf16_target(&combined).unwrap(), long);
    }

    #[test]
    fn garbage_payload_without_string_returns_none() {
        assert!(extract_utf16_target(&[0; 64]).is_none());
        let noisy: Vec<u8> = (0..128).map(|i| (i % 251) as u8).collect();
        assert!(extract_utf16_target(&noisy).is_none());
        assert!(extract_utf16_target(&[]).is_none());
    }

    #[test]
    fn classification_recognizes_enabled_providers() {
        use windows_sys::core::GUID;
        let file_io = GUID {
            data1: 0x90cb_dc39,
            data2: 0x4a3e,
            data3: 0x11d1,
            data4: [0x84, 0xf4, 0x00, 0x00, 0xf8, 0x04, 0x64, 0xe3],
        };
        assert_eq!(kernel_event_category(&file_io, 12), Some("file"));
        let modern_file = GUID {
            data1: 0xedd0_8927,
            data2: 0x9cc4,
            data3: 0x4e65,
            data4: [0xb9, 0x70, 0xc2, 0x56, 0x0f, 0xb5, 0xc2, 0x89],
        };
        assert_eq!(kernel_event_category(&modern_file, 21), Some("file"));
        let reg = GUID {
            data1: 0xae53_722e,
            data2: 0xc863,
            data3: 0x11d2,
            data4: [0xb9, 0x59, 0x00, 0xc0, 0x4f, 0x79, 0xf8, 0xd2],
        };
        assert_eq!(kernel_event_category(&reg, 6), Some("reg"));
        let tcp = GUID {
            data1: 0x9a28_0ac0,
            data2: 0xc8e0,
            data3: 0x11d1,
            data4: [0x84, 0xe2, 0x00, 0xc0, 0x4f, 0xb9, 0x98, 0xa2],
        };
        assert_eq!(kernel_event_category(&tcp, 10), Some("net"));
        let unknown = GUID {
            data1: 0x1111_2222,
            data2: 0x3333,
            data3: 0x4444,
            data4: [0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc],
        };
        assert_eq!(kernel_event_category(&unknown, 1), None);
    }
}

#[cfg(target_family = "windows")]
fn format_guid(guid: &GUID) -> String {
    let data4 = guid.data4;
    format!(
        "{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        guid.data1,
        guid.data2,
        guid.data3,
        data4[0],
        data4[1],
        data4[2],
        data4[3],
        data4[4],
        data4[5],
        data4[6],
        data4[7],
    )
}

#[cfg(target_family = "windows")]
pub fn monitor_minifilter(
    _target_pid: u32,
    api_calls: Arc<Mutex<Vec<String>>>,
    stop_flag: Arc<AtomicBool>,
) {
    let mut calls = api_calls.lock().unwrap();
    calls.push("minifilter:initialized".to_string());
    // 集成点：可在此接入外部深度分析服务（如 CAPE REST API 或 Detonate FastAPI/WebSocket）
    // 将监控到的行为数据（api_calls / ETW 事件）发送到分析服务，获取分析报告后
    // 通过 EngineClient 回调反馈到 GUI 的 sandbox_analysis 文本区域（参考 WinUIApp.cpp::sandbox_panel）
    drop(calls);

    while !stop_flag.load(Ordering::SeqCst) {
        thread::sleep(Duration::from_millis(200));
    }

    let mut calls = api_calls.lock().unwrap();
    calls.push("minifilter:stopped".to_string());

    // 完整网络请求：将遥测数据发送到外部深度分析服务（如 CAPE REST API / Detonate FastAPI）
    let telemetry = api_calls.lock().unwrap();
    let payload = serde_json::json!({
        "source": "everbloom_sandbox",
        "events": telemetry.clone(),
        "target_pid": _target_pid,
    });
    drop(telemetry);

    if let Ok(client) = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
    {
        let _response = client.post("http://localhost:8000/analyze")
            .json(&payload)
            .send();
    }
}

#[cfg(unix)]
fn syscall_name(num: i64) -> Option<&'static str> {
    match num {
        libc::SYS_execve => Some("execve"),
        libc::SYS_openat => Some("openat"),
        libc::SYS_read => Some("read"),
        libc::SYS_write => Some("write"),
        libc::SYS_connect => Some("connect"),
        libc::SYS_accept => Some("accept"),
        libc::SYS_sendto => Some("sendto"),
        libc::SYS_recvfrom => Some("recvfrom"),
        libc::SYS_clone => Some("clone"),
        libc::SYS_fork => Some("fork"),
        libc::SYS_vfork => Some("vfork"),
        libc::SYS_open => Some("open"),
        libc::SYS_close => Some("close"),
        libc::SYS_unlink => Some("unlink"),
        libc::SYS_link => Some("link"),
        libc::SYS_symlink => Some("symlink"),
        libc::SYS_chmod => Some("chmod"),
        libc::SYS_chdir => Some("chdir"),
        libc::SYS_execveat => Some("execveat"),
        _ => None,
    }
}
