//! Cross-checks for the inert synthetic corpus fixtures generated by
//! `python/everbloom_core/synthetic.py`.
//!
//! The fixtures are data-only PE images whose entry point is a single `RET`
//! instruction and whose bodies embed the ASCII safety marker. These tests
//! make sure the Rust runtime (goblin parsing plus the AI feature extractor)
//! agrees with the Python-side feature mirror, so corpora generated offline
//! actually train models against the same representation used at scan time.

use std::path::{Path, PathBuf};

const FIXTURES: &[(&str, bool)] = &[
    // (family, expected malicious-looking traits)
    ("benign_like.bin", false),
    ("packed_like.bin", true),
    ("api_heavy_like.bin", true),
    ("stealth_like.bin", true),
];

const MARKER: &[u8] = b"EVERBLOOM-SYNTHETIC-CORPUS-NOT-MALWARE";

fn fixture_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("tests")
        .join("data")
        .join("synthetic")
        .join(name)
}

fn read_fixture(name: &str) -> Vec<u8> {
    let path = fixture_path(name);
    std::fs::read(&path)
        .unwrap_or_else(|error| panic!("fixture {} unreadable: {error}", path.display()))
}

/// Map an RVA to its file offset using the section table. Returns `None` for
/// headers-only RVAs, matching how the runtime reads section payloads.
fn rva_to_offset(blob: &[u8], rva: u32) -> Option<usize> {
    let e_lfanew = u32::from_le_bytes([
        blob[0x3C],
        blob[0x3D],
        blob[0x3E],
        blob[0x3F],
    ]) as usize;
    let coff = e_lfanew + 4;
    let section_count = u16::from_le_bytes([blob[coff + 2], blob[coff + 3]]) as usize;
    let opt = coff + 20;
    if u16::from_le_bytes([blob[opt], blob[opt + 1]]) != 0x20B {
        return None;
    }
    let mut header = opt + 240;
    for _ in 0..section_count {
        if header + 40 > blob.len() {
            return None;
        }
        let virtual_size = u32::from_le_bytes(blob[header + 8..header + 12].try_into().ok()?);
        let virtual_address = u32::from_le_bytes(blob[header + 12..header + 16].try_into().ok()?);
        let raw_size = u32::from_le_bytes(blob[header + 16..header + 20].try_into().ok()?);
        let raw_ptr = u32::from_le_bytes(blob[header + 20..header + 24].try_into().ok()?);
        if rva >= virtual_address && rva < virtual_address + virtual_size.max(raw_size) {
            let delta = rva - virtual_address;
            if delta < raw_size {
                return Some((raw_ptr as usize) + delta as usize);
            }
            return None;
        }
        header += 40;
    }
    None
}

#[test]
fn fixtures_are_inert_marked_and_parse_as_pe() {
    for (name, _) in FIXTURES {
        let blob = read_fixture(name);
        assert!(
            blob.windows(MARKER.len()).any(|window| window == MARKER),
            "{name} lost the synthetic safety marker"
        );

        let e_lfanew = u32::from_le_bytes([
            blob[0x3C],
            blob[0x3D],
            blob[0x3E],
            blob[0x3F],
        ]) as usize;
        assert_eq!(&blob[e_lfanew..e_lfanew + 4], b"PE\x00\x00", "{name} not a PE");

        let opt = e_lfanew + 4 + 20;
        let entry_rva = u32::from_le_bytes(blob[opt + 16..opt + 20].try_into().unwrap());
        let entry_offset = rva_to_offset(&blob, entry_rva)
            .unwrap_or_else(|| panic!("{name} entry point has no raw mapping"));
        assert_eq!(
            blob[entry_offset], 0xC3,
            "{name} entry stub must stay a single RET"
        );
    }
}

#[test]
fn feature_mirror_separates_benign_from_suspicious_families() {
    let mut benign_entropy = f32::MAX;
    let mut suspicious_entropies = Vec::new();

    for (name, suspicious) in FIXTURES {
        let blob = read_fixture(name);
        let features = everbloom_engine::layers::ai::AiModel::extract_features(&blob);
        assert_eq!(features.len(), 12, "runtime feature contract changed");

        if *suspicious {
            suspicious_entropies.push(features[10]);
        } else {
            benign_entropy = features[10];
            // Benign templates keep TLS absent and plausible timestamps.
            assert_eq!(features[3], 0.0, "{name} unexpectedly carries a TLS table");
        }

        // Every fixture stays under the static analysis sample bound.
        assert!(features[0] <= 1.0 + f32::EPSILON);
    }

    for (index, entropy) in suspicious_entropies.iter().enumerate() {
        // Packed/stealth families must remain clearly separable from benign.
        if index != 1 {
            assert!(
                entropy > &benign_entropy,
                "suspicious family entropy {entropy} <= benign {benign_entropy}"
            );
        }
    }
}

use std::sync::{atomic::AtomicBool, Arc};

use everbloom_engine::{ScanRequest, Scanner};

#[tokio::test]
async fn scanner_reports_unknown_for_benign_synthetic_sample() {
    let blob = read_fixture("benign_like.bin");
    let directory = tempfile::tempdir().expect("temporary directory");
    let sample = directory.path().join("benign_like.bin");
    std::fs::write(&sample, &blob).expect("copy fixture");

    let request = ScanRequest {
        paths: vec![sample],
        timeout_ms: 0,
        sandbox_enabled: false,
        yara_enabled: false,
        ai_enabled: false,
        heuristic_enabled: true,
        clamav_enabled: false,
        ai_threshold: 0.9,
        maximum_file_size: 64 * 1024 * 1024,
        cloud_enabled: false,
        cancelled: Arc::new(AtomicBool::new(false)),
        progress_tx: None,
    };

    let results = Scanner::new()
        .scan_request(request)
        .await
        .expect("scan result");

    assert_eq!(results.len(), 1);
    assert!(
        !results[0].malicious,
        "inert benign fixture must not be flagged: {}",
        results[0].reason
    );
    assert!(
        results[0].error.is_none(),
        "unexpected error: {:?}",
        results[0].error
    );
}
