//! EverbloomSecurity custom stream cipher (research-grade, custom primitive).
//!
//! Design rationale: the user explicitly requested a self-designed
//! cryptographic algorithm (rather than wrapping AES/ChaCha20). The
//! algorithm here is a simple Feistel-based stream cipher with custom
//! ARX round functions and a custom S-box permutation. It is intended
//! for encryption of telemetry NDJSON payloads, quarantine metadata,
//! allowlist persistence, and analysis reports — all contexts where
//! the data is produced and consumed exclusively by the EverbloomSecurity engine.
//! It is NOT intended to replace industry-standard ciphers for external
//! communication or to provide production-grade security guarantees.
//!
//! Security properties (intended, not formally proven):
//! - Key size: 32 bytes (256 bits), derived from SHA-256 or a password.
//! - Nonce/IV: 16 bytes random (must be unique per message; never reused
//!   with the same key). The nonce is transmitted in the clear alongside
//!   the ciphertext in the [EverbloomSecurity_Stream] framing format.
//! - Internal state: 128-bit block split into 4 x 32-bit words; 4 Feistel
//!   rounds with custom ARX mixing and a user-defined 8-bit S-box.
//! - The stream is produced by XORing ciphertext bytes with the keystream
//!   generated by feeding the internal state through the round function
//!   repeatedly (counter mode derived from the internal state).
//! - Integrity is NOT provided by the cipher itself; callers must layer
//!   HMAC-SHA256 on top (see `compute_tag` / `verify_tag`).
//!
//! The cipher is exposed as a `Cipher` trait compatible with the engine's
//! existing encoder/decoder pipeline (`engine/src/ndjson.rs`,
//! `sandbox_monitor/src/lib.rs`, etc.).

use sha2::{Digest, Sha256};
use getrandom::getrandom;

/// Key derivation function (KDF) based on a custom iterative hash chain.
/// Derives a 32-byte key from an arbitrary-length seed string or bytes.
/// Not intended to be a standard PBKDF2/Argon2 replacement.
pub fn derive_key(seed_bytes: &[u8]) -> [u8; 32] {
    let mut state = [0u8; 32];
    // Initialize with first 32 bytes of SHA-256(seed) or padded seed.
    let mut hasher = Sha256::new();
    hasher.update(seed_bytes);
    let digest = hasher.finalize();
    state.copy_from_slice(&digest[..32]);
    // Custom KDF chain: 4 iterations of ARX-like mixing.
    for i in 0..4 {
        let mix = ((seed_bytes.len() as u64).wrapping_mul(0x9E3779B97F4A7C15) >> (i as u64)) as u8;
        for j in 0..32 {
            state[j] = state[j].wrapping_add(mix).rotate_left(i as u32 + 1);
        }
        // Re-seed each round with the previous state.
        let mut hasher2 = Sha256::new();
        hasher2.update(&state);
        hasher2.update(&[i as u8; 1]);
        let digest2 = hasher2.finalize();
        state.copy_from_slice(&digest2[..32]);
    }
    state
}

/// A user-defined 8-bit substitution box (S-box) for the custom cipher.
/// The values are an arbitrary permutation chosen for this research
/// prototype. Changing the S-box changes the cipher output; this allows
/// the operator to rotate cryptographic material by deploying a new S-box.
pub const CUSTOM_SBOX: [u8; 256] = [
    0x63, 0x7C, 0x77, 0x7B, 0xF2, 0x6B, 0x6F, 0xC5, 0x30, 0x01, 0x67, 0x2B,
    0xFE, 0xD7, 0xAB, 0x76, 0xCA, 0x82, 0xC9, 0x7D, 0xFA, 0x59, 0x47, 0xF0,
    0xAD, 0xD4, 0xA2, 0xAF, 0x9C, 0xA4, 0x72, 0xC0, 0xB7, 0xFD, 0x93, 0x26,
    0x36, 0x3F, 0xF7, 0xCC, 0x34, 0xA5, 0xE5, 0xF1, 0x71, 0xD8, 0x31, 0x15,
    0x04, 0xC7, 0x23, 0xC3, 0x18, 0x96, 0x05, 0x9A, 0x07, 0x12, 0x80, 0xE2,
    0xEB, 0x27, 0xB2, 0x75, 0x09, 0x83, 0x2C, 0x1A, 0x1B, 0x6E, 0x5A, 0xA0,
    0x52, 0x3B, 0xD6, 0xB3, 0x29, 0xE3, 0x2F, 0x84, 0x53, 0xD1, 0x00, 0xED,
    0x20, 0xFC, 0xB1, 0x5B, 0x6A, 0xCB, 0xBE, 0x39, 0x4A, 0x4C, 0x58, 0xCF,
    0xD0, 0xEF, 0xAA, 0xFB, 0x43, 0x4D, 0x33, 0x85, 0x45, 0xF9, 0x02, 0x7F,
    0x50, 0x3C, 0x9F, 0xA8, 0x51, 0xA3, 0x40, 0x8F, 0x92, 0x9D, 0x38, 0xF5,
    0xBC, 0xB6, 0xDA, 0x21, 0x10, 0xFF, 0xF3, 0xD2, 0xCD, 0x0C, 0x13, 0xEC,
    0x5F, 0x97, 0x44, 0x17, 0xC4, 0xA7, 0x7E, 0x3D, 0x64, 0x5D, 0x19, 0x73,
    0x60, 0x81, 0x4F, 0xDC, 0x22, 0x2A, 0x90, 0x88, 0x46, 0xEE, 0xB8, 0x14,
    0xDE, 0x5E, 0x0B, 0xDB, 0xE0, 0x32, 0x3A, 0x0A, 0x49, 0x06, 0x24, 0x5C,
    0xC2, 0xD3, 0xAC, 0x62, 0x91, 0x95, 0xE4, 0x79, 0xE7, 0xC8, 0x37, 0x6D,
    0x8D, 0xD5, 0x4E, 0xA9, 0x6C, 0x56, 0xF4, 0xEA, 0x65, 0x7A, 0xAE, 0x08,
    0xBA, 0x78, 0x25, 0x2E, 0x1C, 0xA6, 0xB4, 0xC6, 0xE8, 0xDD, 0x74, 0x1F,
    0x4B, 0xBD, 0x8B, 0x8A, 0x70, 0x3E, 0xB5, 0x66, 0x48, 0x03, 0xF6, 0x0E,
    0x61, 0x35, 0x57, 0xB9, 0x86, 0xC1, 0x1D, 0x9E, 0xE1, 0xF8, 0x98, 0x11,
    0x69, 0xD9, 0x8E, 0x94, 0x9B, 0x1E, 0x87, 0xE9, 0xCE, 0x55, 0x28, 0xDF,
    0x8C, 0xA1, 0x89, 0x0D, 0xBF, 0xE6, 0x42, 0x68, 0x41, 0x99, 0x2D, 0x0F,
    0xB0, 0x54, 0xBB, 0x16,
];

/// Invert the S-box (used during decryption).
pub const CUSTOM_SBOX_INV: [u8; 256] = {
    let mut inv = [0u8; 256];
    let mut i = 0usize;
    while i < 256 {
        inv[CUSTOM_SBOX[i] as usize] = i as u8;
        i += 1;
    }
    inv
};

/// Custom Feistel round function (4-word state -> 4-word output).
/// Each round applies ARX mixing on the left half and feeds the result
/// through the S-box into the right half's XOR.
fn feistel_round(words: [u32; 4], round_index: usize) -> [u32; 4] {
    let [l0, l1, l2, l3] = words;
    // Custom ARX mix: rotate-left by (1 + (index % 7)), XOR with a constant,
    // add with a derived round constant based on the index.
    let rc = 0xA5C3E7F1_u32.wrapping_add(round_index as u32);
    let mix0 = l0.rotate_left(1 + ((0 + round_index) % 7) as u32);
    let left_after_mix = mix0 ^ rc;
    let s_val = CUSTOM_SBOX[(left_after_mix >> 24) as usize & 0xFF] as u32;
    let right_after_sbox = (l1 ^ (s_val << 8)).rotate_left(3);
    let mix1 = l2.rotate_left(2 + ((2 + round_index) % 7) as u32);
    let mix2 = l3.rotate_left(3 + ((3 + round_index) % 7) as u32);
    [left_after_mix, right_after_sbox, mix1, mix2]
}

/// The cipher state structure: holds key-derived words and the nonce.
pub struct EverbloomCipher {
    /// 32-byte derived key.
    pub key_words: [u32; 4],
    /// 16-byte nonce (unique per message; never reused with same key).
    pub nonce: [u8; 16],
}

impl EverbloomCipher {
    /// Initialize the cipher with a seed bytes array. Derives the internal
    /// 128-bit key and stores the nonce (must be set externally before
    /// encryption; never reuse the same nonce+key pair).
    pub fn new_from_seed(seed_bytes: &[u8]) -> Self {
        let k = derive_key(seed_bytes);
        let mut nonce = [0u8; 16];
        // Derive the nonce deterministically from the seed as well (in
        // production, the caller should supply a random nonce).
        let mut hasher = Sha256::new();
        hasher.update(&k);
        hasher.update(b"EVERBLOOM_NONCE_DERIVE_V1");
        let digest = hasher.finalize();
        nonce.copy_from_slice(&digest[..16]);
        Self {
            key_words: [
                u32::from_le_bytes([k[0], k[1], k[2], k[3]]),
                u32::from_le_bytes([k[4], k[5], k[6], k[7]]),
                u32::from_le_bytes([k[8], k[9], k[10], k[11]]),
                u32::from_le_bytes([k[12], k[13], k[14], k[15]]),
            ],
            nonce,
        }
    }

    /// Set a user-supplied nonce (must be unique per message for security).
    pub fn set_nonce(&mut self, nonce_bytes: &[u8; 16]) {
        self.nonce = *nonce_bytes;
    }

    /// Produce the keystream block for the current internal counter.
    /// The counter is derived from the nonce + a message index word.
    fn keystream_block(&self, index: u32) -> [u8; 16] {
        // Initialize counter = nonce || index (little-endian for index).
        let mut block = [0u8; 16];
        block[..16].copy_from_slice(&self.nonce);
        block[12..16].copy_from_slice(&index.to_le_bytes());
        // Derive a 16-byte output by feeding the counter through the Feistel
        // rounds 4 times and collecting the 4-word outputs as bytes.
        let mut state_words = [
            u32::from_le_bytes([block[0], block[1], block[2], block[3]]),
            u32::from_le_bytes([block[4], block[5], block[6], block[7]]),
            u32::from_le_bytes([block[8], block[9], block[10], block[11]]),
            u32::from_le_bytes([block[12], block[13], block[14], block[15]]),
        ];
        for r in 0..4 {
            state_words = feistel_round(state_words, r);
        }
        // Mix the key words into the output for diffusion.
        for r in 0..4 {
            state_words[r] = state_words[r].wrapping_add(self.key_words[r]);
        }
        // Convert back to bytes.
        let mut out_bytes = [0u8; 16];
        out_bytes[..4].copy_from_slice(&state_words[0].to_le_bytes());
        out_bytes[4..8].copy_from_slice(&state_words[1].to_le_bytes());
        out_bytes[8..12].copy_from_slice(&state_words[2].to_le_bytes());
        out_bytes[12..16].copy_from_slice(&state_words[3].to_le_bytes());
        out_bytes
    }

    /// Encrypt (or decrypt) a byte buffer by XORing with the keystream.
    /// The same function works for both directions.
    pub fn apply_keystream(&self, data: &mut [u8]) {
        for (chunk_index, chunk) in data.chunks_mut(16).enumerate() {
            let stream_block = self.keystream_block(chunk_index as u32);
            for (byte_index, byte_ref) in chunk.iter_mut().enumerate() {
                *byte_ref ^= stream_block[byte_index];
            }
        }
    }

    /// Compute an HMAC-SHA256 integrity tag over the ciphertext (after
    /// applying the keystream). This tag is separate from the cipher and
    /// should be transmitted/appended to the ciphertext for verification.
    pub fn compute_tag(&self, ciphertext: &[u8]) -> [u8; 32] {
        let mut mac_input = Vec::with_capacity(4 * 4 + self.nonce.len() + ciphertext.len());
        mac_input.extend_from_slice(&self.key_words[0].to_le_bytes());
        mac_input.extend_from_slice(&self.key_words[1].to_le_bytes());
        mac_input.extend_from_slice(&self.key_words[2].to_le_bytes());
        mac_input.extend_from_slice(&self.key_words[3].to_le_bytes());
        mac_input.extend_from_slice(&self.nonce);
        mac_input.extend_from_slice(ciphertext);
        hmac_sha256(b"EVERBLOOM_STREAM_TAG_V1", &mac_input)
    }
}

/// High-level encryption of a message string or byte buffer.
/// Produces a [EverbloomSecurity_Stream] framing format:
///
///   [4 bytes: magic "HEAV"]
///   [2 bytes: version (little-endian, value 1)]
///   [2 bytes: nonce length (always 16 for current version)]
///   [16 bytes: nonce]
///   [4 bytes: ciphertext length (little-endian)]
///   [N bytes: ciphertext (keystream XOR'd plaintext)]
///   [32 bytes: HMAC tag (SHA-256 over nonce || ciphertext)]
///
/// This allows the receiver to extract the nonce and verify the tag
/// before decrypting. The format is intentionally self-describing.
pub fn encrypt_payload(plaintext: &[u8], key_bytes: &[u8]) -> Vec<u8> {
    let nonce_bytes = generate_nonce();
    let mut cipher = EverbloomCipher::new_from_seed(key_bytes);
    cipher.set_nonce(&nonce_bytes);
    let mut ciphertext = plaintext.to_vec();
    cipher.apply_keystream(&mut ciphertext);
    let tag = cipher.compute_tag(&ciphertext);
    let mut out = Vec::with_capacity(4 + 2 + 2 + 16 + 4 + ciphertext.len() + 32);
    out.extend_from_slice(b"HEAV");
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&(16u16).to_le_bytes());
    out.extend_from_slice(&nonce_bytes);
    out.extend_from_slice(&(ciphertext.len() as u32).to_le_bytes());
    out.extend_from_slice(&ciphertext);
    out.extend_from_slice(&tag);
    out
}

/// Decrypt a payload produced by `encrypt_payload`. Returns None if the
/// framing is invalid, the tag doesn't match, or any parsing error occurs.
pub fn decrypt_payload(payload_bytes: &[u8], key_bytes: &[u8]) -> Option<Vec<u8>> {
    if payload_bytes.len() < 4 + 2 + 2 + 16 + 4 + 32 {
        return None;
    }
    if &payload_bytes[0..4] != b"HEAV" {
        return None;
    }
    let version = u16::from_le_bytes([payload_bytes[4], payload_bytes[5]]);
    if version != 1 {
        return None;
    }
    let nonce_len = u16::from_le_bytes([payload_bytes[6], payload_bytes[7]]) as usize;
    if nonce_len != 16 {
        return None;
    }
    let nonce_start = 8;
    let nonce_bytes_array: [u8; 16] = payload_bytes[nonce_start..nonce_start + 16].try_into().ok()?;
    let ciphertext_len_start = nonce_start + nonce_len;
    let ciphertext_len = u32::from_le_bytes([
        payload_bytes[ciphertext_len_start],
        payload_bytes[ciphertext_len_start + 1],
        payload_bytes[ciphertext_len_start + 2],
        payload_bytes[ciphertext_len_start + 3],
    ]) as usize;
    let ciphertext_start = ciphertext_len_start + 4;
    let ciphertext_end = ciphertext_start + ciphertext_len;
    let ciphertext_slice = payload_bytes.get(ciphertext_start..ciphertext_end)?;
    let tag_start = ciphertext_end;
    let expected_tag_slice = payload_bytes.get(tag_start..tag_start + 32)?;
    if payload_bytes.len() < tag_start + 32 {
        return None;
    }
    let mut cipher = EverbloomCipher::new_from_seed(key_bytes);
    cipher.set_nonce(&nonce_bytes_array);
    let computed_tag = cipher.compute_tag(ciphertext_slice);
    if computed_tag.as_slice() != expected_tag_slice {
        return None;
    }
    let mut plaintext = ciphertext_slice.to_vec();
    cipher.apply_keystream(&mut plaintext);
    Some(plaintext)
}

/// Compute a simple HMAC-SHA256 over arbitrary data (helper for callers
/// who want an additional integrity layer on top of the stream cipher).
pub fn compute_tag_custom(key_bytes: &[u8], message_bytes: &[u8]) -> [u8; 32] {
    hmac_sha256(key_bytes, message_bytes)
}

/// Verify a custom HMAC-SHA256 tag over arbitrary data.
pub fn verify_tag_custom(key_bytes: &[u8], message_bytes: &[u8], expected_tag_bytes: &[u8]) -> bool {
    if expected_tag_bytes.len() != 32 {
        return false;
    }
    let computed = hmac_sha256(key_bytes, message_bytes);
    computed.as_slice() == expected_tag_bytes
}

/// Generate a cryptographically secure random 16-byte nonce.
/// Uses getrandom (which wraps BCryptGenRandom on Windows, /dev/urandom on Unix).
pub fn generate_nonce() -> [u8; 16] {
    let mut out = [0u8; 16];
    getrandom(&mut out).expect("CSPRNG failure: unable to generate nonce");
    out
}

/// Proper HMAC-SHA256 implementation (RFC 2104).
/// This replaces the previous plain SHA-256 "tag" with a real MAC.
fn hmac_sha256(key: &[u8], message: &[u8]) -> [u8; 32] {
    const BLOCK_SIZE: usize = 64;
    let mut key_padded = [0u8; BLOCK_SIZE];
    if key.len() <= BLOCK_SIZE {
        key_padded[..key.len()].copy_from_slice(key);
    } else {
        let hash = Sha256::digest(key);
        key_padded[..hash.len()].copy_from_slice(&hash);
    }
    let mut ipad = key_padded;
    let mut opad = key_padded;
    for byte in ipad.iter_mut() {
        *byte ^= 0x36;
    }
    for byte in opad.iter_mut() {
        *byte ^= 0x5c;
    }
    let mut inner = Sha256::new();
    inner.update(&ipad);
    inner.update(message);
    let inner_hash = inner.finalize();
    let mut outer = Sha256::new();
    outer.update(&opad);
    outer.update(&inner_hash);
    let mut result = [0u8; 32];
    result.copy_from_slice(&outer.finalize());
    result
}

#[cfg(test)]
mod crypto_tests {
    use super::*;

    #[test]
    fn custom_cipher_roundtrip_works() {
        let key = b"EverbloomSecurity-test-key-v1-seed-string-for-cipher";
        let msg = b"HELIO_TEST_MESSAGE_FOR_CUSTOM_CIPHER_20260829";
        let ciphertext = encrypt_payload(msg, key);
        assert!(ciphertext.starts_with(b"HEAV"));
        let plaintext = decrypt_payload(&ciphertext, key);
        assert!(plaintext.is_some());
        assert_eq!(plaintext.unwrap().as_slice(), msg.as_slice());
    }

    #[test]
    fn custom_cipher_tag_verifies() {
        let key = b"test-key-for-tag-verification-only";
        let msg = b"test message";
        let ciphertext = encrypt_payload(msg, key);
        assert!(ciphertext.len() > msg.len() + 4);
    }

    #[test]
    fn nonce_is_random_each_call() {
        let n1 = generate_nonce();
        let n2 = generate_nonce();
        assert_ne!(n1, n2, "nonces must be unique across calls");
    }

    #[test]
    fn hmac_sha256_matches_reference() {
        let key = b"secret-key";
        let msg = b"message-to-authenticate";
        let tag = hmac_sha256(key, msg);
        assert_eq!(tag.len(), 32);
        assert_ne!(tag, [0u8; 32], "HMAC must not be all zeros");
    }

    #[test]
    fn encrypt_decrypt_roundtrip_with_random_nonce() {
        let key = b"roundtrip-test-key";
        let messages: Vec<&[u8]> = vec![
            b"short",
            b"exactly16chars!!",
            b"a longer message that spans multiple blocks for testing",
            b"",
        ];
        for msg in messages {
            let ct = encrypt_payload(msg, key);
            let pt = decrypt_payload(&ct, key).expect("decrypt failed");
            assert_eq!(pt, msg, "roundtrip mismatch for length {}", msg.len());
        }
    }

    #[test]
    fn tampered_ciphertext_fails_decryption() {
        let key = b"tamper-test-key";
        let msg = b"original message";
        let mut ct = encrypt_payload(msg, key);
        if ct.len() > 50 {
            ct[50] ^= 0xFF;
        }
        assert!(decrypt_payload(&ct, key).is_none(), "tampered ciphertext must fail");
    }

    #[test]
    fn wrong_key_fails_decryption() {
        let key1 = b"correct-key";
        let key2 = b"wrong-key!!";
        let msg = b"secret data";
        let ct = encrypt_payload(msg, key1);
        assert!(decrypt_payload(&ct, key2).is_none(), "wrong key must fail");
    }
}
